const nameOnPass = "Bryan";
console.log(`Passenger Name: ${nameOnPass}`);
const nameOnId = "Bryan";
const nameMatch = nameOnPass === nameOnId;
console.log(`ID confirmed: ${nameMatch}`);
const length = 18;
const doesLengthPass = length < 30;
const height = 40;
const doesHeightPass = height < 55;
const isHandBaggageEligible = doesHeightPass && doesLengthPass;
console.log(`Is hand baggage eligible? ${isHandBaggageEligible}`);
const flightDes = "New York";
const returnFrom = "Seattle";
const isRoundTrip = flightDes === returnFrom;
console.log(`Round Trip Check? ${isRoundTrip}`);
const bookings = 10;
const totalCapacity = 25;
const isFlightAvailable = bookings <= totalCapacity;
console.log(`Are seats available? ${isFlightAvailable}`);
document.getElementById("name").innerHTML = nameOnPass;
document.getElementById("id").innerHTML = nameMatch;
document.getElementById("bag").innerHTML = isHandBaggageEligible;
document.getElementById("des").innerHTML = isRoundTrip;
document.getElementById("seat").innerHTML = isFlightAvailable;
